apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-bus-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: event-bus
spec:
  clusterIP: None # means headless
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    event-bus: rabbitmq