version: "3.8"

services:  
    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=myDbConn3ct10nPassw0rD!@
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - tasktronic-network

    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e789654
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq/mnesia
        networks: 
            - tasktronic-network

    identity:
        container_name: identity
        image: stefantestdocker/tasktronic-identity-service
        build:
            context: ./TaskTronicApp
            dockerfile: ./TaskTronic.Identity/Dockerfile
        ports: 
            - "5000:80"
        env_file: TaskTronicApp/TaskTronic/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskTronicIdentity;User Id=sa; Password=myDbConn3ct10nPassw0rD!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - tasktronic-network
        depends_on:
            - data
            
    drive:
        container_name: drive
        image: stefantestdocker/tasktronic-drive-service
        build:
            context: ./TaskTronicApp
            dockerfile: ./TaskTronic.Drive/Dockerfile
        ports: 
            - "5002:80"
        env_file: TaskTronicApp/TaskTronic/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskTronicDrive;User Id=sa; Password=myDbConn3ct10nPassw0rD!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - tasktronic-network
        depends_on:
            - data
            - messages

    notifications:
        container_name: notifications
        image: stefantestdocker/tasktronic-notifications-service
        build:
            context: ./TaskTronicApp
            dockerfile: ./TaskTronic.Notifications/Dockerfile
        ports: 
            - "5008:80"
        env_file: TaskTronicApp/TaskTronic/Common.env
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - tasktronic-network
        depends_on:
            - drive
            - messages
            
    statistics:
        container_name: statistics
        image: stefantestdocker/tasktronic-statistics-service
        build:
            context: ./TaskTronicApp
            dockerfile: ./TaskTronic.Statistics/Dockerfile
        ports: 
            - "5004:80"
        env_file: TaskTronicApp/TaskTronic/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskTronicStatistics;User Id=sa; Password=myDbConn3ct10nPassw0rD!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - tasktronic-network
        depends_on:
            - data
            - messages
            
    admin:
        container_name: admin
        image: stefantestdocker/tasktronic-admin-service
        build:
            context: ./TaskTronicApp
            dockerfile: ./TaskTronic.Admin/Dockerfile
        ports: 
            - "5010:80"
        env_file: TaskTronicApp/TaskTronic/Common.env
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - tasktronic-network
        depends_on:
            - identity
            - drive
            
    drive.gateway:
        container_name: drive.gateway
        image: stefantestdocker/tasktronic-drivegateway-service
        build:
            context: ./TaskTronicApp
            dockerfile: ./TaskTronic.Drive.Gateway/Dockerfile
        ports: 
            - "5006:80"
        env_file: TaskTronicApp/TaskTronic/Common.env
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - tasktronic-network
        depends_on:
            - statistics
            - drive

    watchdog:
        container_name: watchdog
        image: stefantestdocker/tasktronic-watchdog-service
        build:
            context: ./TaskTronicApp
            dockerfile: ./TaskTronic.Watchdog/Dockerfile
        ports: 
            - "5013:80"
        restart: on-failure
        networks: 
            - tasktronic-network
        depends_on:
            - statistics
            - drive
            - identity

    angular:
        container_name: angular-client
        image: stefantestdocker/tasktronic-client-service
        build:
             context: ./TaskTronic.Client
             dockerfile: ./Dockerfile
        ports:
            - "4200:4200"
        restart: on-failure
        networks:
            - tasktronic-network
        depends_on:
            - identity
networks:
    tasktronic-network:

volumes:
    sqldata:
    rabbitmq:
    data-protection: